### ISSUE TITLE
Program nebere argumenty dle specifikace

### ISSUE THREAD

**Issue by xtompok** [zuravskm/prg2_du3#1]
```
python3 network_analyst.py --net data/testdata_utm.geojson --out out.geojson --from 50 14 --to 50 15
Loading input data...
Inappropriate path to input file.
```
Kromě toho také dle zadání mohou být argumenty v libovolném pořadí. Doporučuji pro parsování argumentů příkazové řádky využít modul `click` případně `argparse`.

**Comment by RosBer97** [comment]
Upravena dokumentace.
