### ISSUE TITLE
Bylo by vhodné převádět vstupní data do kartézského systému automaticky a nevyžadovat to po uživatelích

### ISSUE THREAD

**Issue by xtompok** [zuravskm/prg2_du3#3]
Většina z dnes běžně dostupných dat je ve WGS-84, takže by bylo vhodné, aby si program sám převedl při načítání tato data do nějakého kartézského systému (třeba UTM) a nevyžadoval tuto konverzi po uživatelích. Upravit kód by nemělo být nijak náročné a uživateli to ušetří čas a znalosti, které nemusí mít. Nevýhodou bude pomalejší běh programu, ale to pro tento případ nevadí. 

Doporučuji si vytvořit jeden globální transformační objekt a ten používat pro konverze, protože vytváření tranformačního objektu pro každou souřadnici významně prodlužuje dobu běhu (nebo aspoň takové jsou mé zkušenosti z dřívějška).

**Comment by RosBer97** [comment]
Upravil jsem skript a odteď vstupy ve wgs84 převádíme do web mercatora. + jemná úprava dokumentace a přídání testovacích dat ve wgs84.
